name: abstergo_flutter
description: A new webkiosk.

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager: "^0.1.0"
  cloud_firestore: 
  flutter_redux: "^0.5.0"
  redux_thunk: "^0.2.0"
  fluro: "^1.3.1"
  intl: "^0.15.2"
  local_notifications: "^0.0.1"
  shared_preferences: "^0.4.0"
  tkiosk:
    path: ../tkiosk/
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
