name: abstergo_flutter
description: A new webkiosk.

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager: 
  cloud_firestore: 0.7.3
  firebase_auth: 0.5.12
  firebase_remote_config: 0.0.5
  flutter_redux: 0.5.0
  intl: 0.15.2
  local_notifications: 0.0.1
  sentry: any
  shared_preferences: 0.4.0
  tkiosk:
    path: "../tkiosk/"
     
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
   - assets/ic_launcher.png
   - assets/ic_launcher_round.png
   - assets/ic_launcher_back.png
   - assets/login_background.png
   - assets/background.png
   
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/Product-Sans-Regular.ttf
        - asset: fonts/Product-Sans-Italic.ttf
          style: italic
        - asset: fonts/Product-Sans-Bold.ttf
          weight: 700
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
    - family: Titillium
      fonts:
        - asset: fonts/TitilliumWeb-Regular.ttf
        - asset: fonts/TitilliumWeb-Light.ttf
          weight: 300
        - asset: fonts/TitilliumWeb-Bold.ttf
          weight: 700
        - asset: fonts/TitilliumWeb-Italic.ttf
          style: italic
